name: docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-docker-images:
    name: build-docker-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: "Rebuild secondstate/tencent-tensorflow-scf:latest"
        uses: docker/build-push-action@v1
        with:
          dockerfile: .devcontainer/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: secondstate/tencent-tensorflow-scf
          tags: latest
          add_git_labels: true
          always_pull: true
